- name: Reload "systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart "tailscale-proxy"
  become: true
  ansible.builtin.systemd:
    name: tailscale-proxy
    state: restarted
    enabled: yes
